### ISSUE TITLE
Injected CSS/JS not rendering in team tab html files

### ISSUE THREAD

**Issue by BustosAndrew** [pnp/generator-teams#190] opened 2021-03-06 09:10 UTC
After deploying to my domain at [www.boxintegrationapi.com](url) I only see a "Loading..." element. gulp injects all the files needed into the html files under the web folder. However, no css appears to be rendering, and neither does the injected js. I get the following errors in the chrome console:

Uncaught SyntaxError: Unexpected token '<' client.js:1
Uncaught ReferenceError: integration is not defined at (index):18

I am not sure why this is happening or how to fix it. integration is the name of my package that tries calling the following line:

`integration.render(
        integration.BoxTabConfig,
        document.getElementById('app'),
        {}
      )`
in a script element. This only seems to work locally.

**To Reproduce**
1. Generate a teams tab app with config tab enable
2. Run gulp manifest so you can upload it as a custom app in teams
3. Run gullp build
4. Remove the dist file reference in gitignore
5. Deploy the dist folder to whatever web hosting service
6. Upload the manifest to teams, and select whatever team to add the tab to
7. Observe results

**Expected behavior**
All css and js to render/load in the tab html files.

Image of the problem: <blockquote class="imgur-embed-pub" lang="en" data-id="a/yUVienJ"  ><a href="//imgur.com/a/yUVienJ">Team tab not working</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

I am using the latest version of everything.

**Additional information**
I am deploying this on netlify, with environment variables stored on there.
Here is my GitHub: https://github.com/BustosAndrew/Integration

**Comment by wictorwilen** [comment] 2021-03-06 11:24
Thanks @BustosAndrew - the firs thing that comes to my mind is that have you ensured that you've built manifest with the correct host name/URL. That is, in your `.env` file you have set `HOSTNAME` to www.boxintegrationapi.com?

**Comment by BustosAndrew** [comment] 2021-03-06 16:18
Yes I checked.

**Comment by wictorwilen** [comment] 2021-03-06 17:28
When you open Teams via browser, can you using the network dev tools verify that the JS and CSS is downloaded

**Comment by BustosAndrew** [comment] 2021-03-07 00:21
This is what I get when I upload on the web app:

```
Some messages have been moved to the Issues panel.
2-vendor.min-6345272.js:1 JQMIGRATE: Migrate is installed, version 3.0.1
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.975Z:authBootstrap:{}:"https://chatsvcagg.teams.microsoft.com token from local storage was expired"
warn @ 3-app-prefetch.min-4774e99.js:1
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.975Z:authBootstrap:{}:"https://api.spaces.skype.com token from local storage was expired"
warn @ 3-app-prefetch.min-4774e99.js:1
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.975Z:authBootstrap:{}:"Unable to find cached tokens"
warn @ 3-app-prefetch.min-4774e99.js:1
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.976Z:CDLWorkerManager:{"hostRendererId":"MainRenderer","component":"CDLGlobalState"}:"Global state has reached checkpoint bootstrapped"
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.976Z:CDLWorkerManager:{"component":"CDLServer","hostRendererId":"MainRenderer"}:"Booted up server"
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.976Z:CDLWorkerManager:{"hostRendererId":"MainRenderer","component":"CDLGlobalState"}:"Global state has reached checkpoint Server_Start"
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:19.976Z:CDLWorkerManager:{"hostRendererId":"MainRenderer","component":"CDLGlobalState"}:"Global state has reached checkpoint loaded"
_:22 [Index] Loading stylesheet: https://statics.teams.cdn.office.net/hashed/stylesheets.theme-defaultV2.min-7333588.css
The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

_:22 [Index] Loaded stylesheet: https://statics.teams.cdn.office.net/hashed/stylesheets.theme-defaultV2.min-7333588.css
_#/?lm=deeplink&lmsrc=officeWaffle&login_hint_safe=BustosAndrew@soloiron.onmicrosoft.com:1 The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

precompiled-web-worker-4f608a5841d157b7.js:1 e
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:20.430Z:CDLWorkerManager:{"hostRendererId":"MainRenderer","component":"CDLGlobalState"}:"Global state has reached checkpoint health_checked"
3-app-prefetch.min-4774e99.js:1 2021-03-07T00:17:20.430Z:CDLWorkerManager:{"hostRendererId":"MainRenderer","component":"CDLGlobalState"}:"Global state has reached checkpoint initialized"
precompiled-web-worker-4f608a5841d157b7.js:1 Uncaught (in promise) Objectcode: "Disabled"context: "WorkerInitialization"message: "Sync Engine not enabled"name: ""__proto__: Object
3.2-app.min-7d530ac.js:1 Cleaned the join location
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. newCounter
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. newLogger
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. event
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. customEvent
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. notifyUserbiEvents
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. sendPackedUserbiEvents
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. findScenario
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. findScenarioByNameAndId
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. timestamp
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. newScenario
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. setContext
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. getContext
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. createScenarioWithoutStarting
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. findAllScenariosByName
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. getActiveScenarioNames
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. setCommonRequestHeaders
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. unblockTelemetry
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. initTimers
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. addTimelineMarker
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. populateUserInfo
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. populateUserRegion
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. setIsLaunchAsync
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. setServiceWorkersStatus
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. populateUserResourcesSettingsContext
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. populateSimplifiedUxStatus
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. flush
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. hashUriParamsPII
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. registerEventDecorator
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. clearAllScenarios
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 Logging Service not initialized yet. deviceId
(anonymous) @ 3.2-app.min-7d530ac.js:1
3.2-app.min-7d530ac.js:1 SettingsService: Refreshing settings. Array(1)
3.2-app.min-7d530ac.js:1 SettingsService: Refreshing settings. Array(1)
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:21.071Z AppCache: App Cache is not defined on the desktop app
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:21.079Z transportDependencyProviderService: transport can't be initialized, settingsService is enabled - true,
          desktop is pluginless - false,
          destop is Hwa - true,
          is desktop client - false,
          slimcore enabled - false
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
_#/apps?intent=2&category=16&autoNavigationOnDone=true&skipInstalledSuccess=false&filterByPersonal=false&storeLaunchFromChat=false:1 The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.002Z ScreenSharingService: ipc not available
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.188Z EC::HybridContentVisibilityManager: Error caught in loadServices: {"reason":"service_not_enabled_orchestration"}.
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.188Z Orchestrator: EC::ExperienceContainerFeatureOrchestrationStep loadServices failed: "service_not_enabled_orchestration".
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.228Z Analytics panel: Panel data not present in context, routing or state service. No way to infer panel data for panel view. Falling back to "undefined"
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.229Z Analytics panel: Panel data not present in context, routing or state service. No way to infer panel data for panel view. Falling back to "undefined"
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.289Z Orchestrator: ExperienceContainerFeatureOrchestrationStep failed.
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.374Z UnifiedPresenceService: [canSubscribe] Trouter endpoint id is not defined yet
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 Error: Failed to resolve: the task is already resolved
    at o._checkState (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6391423)
    at o.resolve (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6390231)
    at Object.successFunc (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6614475)
    at https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6392936
    at a (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6387250)
    at o._resolveCallback (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6392915)
    at https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6392807
    at Array.forEach (<anonymous>)
    at o._resolveSuccesses (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6392725)
    at o._addCallbackSet (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:6389237) Unhandled error caught in promise chain
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
2-vendor.min-6345272.js:1 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: Thu Mar 04 2021 13:11:06 GMT+0000, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:656822)
    at https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:667945
    at https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:667996
    at me (https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:668286)
    at https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:668676
    at _e (https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:668738)
    at Function.c [as utc] (https://statics.teams.cdn.office.net/hashed/2-vendor.min-6345272.js:1:654577)
    at t.shouldFetchEngagementProfile (https://statics.teams.cdn.office.net/hashed/lazy-ng1-mod-engagement-surface-services.min-07842a1.js:1:91734)
    at https://statics.teams.cdn.office.net/hashed/lazy-ng1-mod-engagement-surface-services.min-07842a1.js:1:75608
    at f (https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:127:115)
v @ 2-vendor.min-6345272.js:1
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:23.799Z callingSupportService: Found phone number in AAD but not in BVD [phonenumber]
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
3.1-app.min-2a3d537.js:1 Uncaught (in promise) background blurring is not enabled
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:24.407Z UnifiedPresenceService: [canSubscribe] Trouter endpoint id is not defined yet
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:24.545Z callingMultiWindowService: Function being called outside the context of Calling MW Rollout phases 1 or 2
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
amer.ng.msg.teams.microsoft.com/v1/users/ME/conversations/19%3A625508bc1d7d479991c26ed956352811%40thread.tacv2/properties?name=favorite&requirePermanentJoinedState=true:1 Failed to load resource: the server responded with a status of 400 ()
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.586Z [setFavoriteSettingForChannelInternal] Failed to [setFavoriteConversationProperty] with objectId "19:625508bc1d7d479991c26ed956352811@thread.tacv2".
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.586Z [setFavoriteSettingForChannelInternal] Failed to [setFollowedConversationProperty] with objectId "19:625508bc1d7d479991c26ed956352811@thread.tacv2".
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.587Z [toggleFavoriteSettingForChannel] Failed to fav state on channel "19:625508bc1d7d479991c26ed956352811@thread.tacv2" Error: {"statusCode":400,"headers":{"cache-control":"no-store, must-revalidate, no-cache","content-length":"63","content-type":"application/json; charset=utf-8","contextid":"tcid=0,server=msgapi-production-wus-azsc1-5-22,cv=ATiwfsJZYECrBw3yZCo4KA.0","pragma":"no-cache"},"errorMessage":"User is no longer in thread roster.","errorCode":0,"request":{}}.
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
amer.ng.msg.teams.microsoft.com/v1/users/ME/conversations/19%3Ab1f9cd9183854104a85a45eb955c9bb1%40thread.tacv2/properties?name=favorite&requirePermanentJoinedState=true:1 Failed to load resource: the server responded with a status of 400 ()
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.918Z [setFavoriteSettingForChannelInternal] Failed to [setFavoriteConversationProperty] with objectId "19:b1f9cd9183854104a85a45eb955c9bb1@thread.tacv2".
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.918Z [setFavoriteSettingForChannelInternal] Failed to [setFollowedConversationProperty] with objectId "19:b1f9cd9183854104a85a45eb955c9bb1@thread.tacv2".
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:26.918Z [toggleFavoriteSettingForChannel] Failed to fav state on channel "19:b1f9cd9183854104a85a45eb955c9bb1@thread.tacv2" Error: {"statusCode":400,"headers":{"cache-control":"no-store, must-revalidate, no-cache","content-length":"63","content-type":"application/json; charset=utf-8","contextid":"tcid=0,server=msgapi-production-wus-azsc1-5-22,cv=3UfVZHuEj0WUkPjjwB3b4g.0","pragma":"no-cache"},"errorMessage":"User is no longer in thread roster.","errorCode":0,"request":{}}.
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.643Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.643Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.643Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.643Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: null
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:28.644Z value not found in enum type. value: 
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:114 2021-03-07T00:17:41.665Z AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
0-angular-jquery.min-eee9041.js:1 Refused to set the document's base URI to 'https://teams.microsoft.com/_#/conversations/General?threadId=19:9fd294b76a5940108190f8e16f3604e7@thread.tacv2&ctx=channel' because it violates the following Content Security Policy directive: "base-uri *.protection.outlook.com".

(anonymous) @ 0-angular-jquery.min-eee9041.js:1
_#/conversations/General?threadId=19:9fd294b76a5940108190f8e16f3604e7@thread.tacv2&ctx=channel:1 Autofocus processing was blocked because a document's URL has a fragment '#/conversations/General?threadId=19:9fd294b76a5940108190f8e16f3604e7@thread.tacv2&ctx=channel'.
0-angular-jquery.min-eee9041.js:114 TypeError: Cannot read property 'toLowerCase' of undefined
    at e.getExtensionDefinition (https://statics.teams.cdn.office.net/hashed/3.2-app.min-7d530ac.js:1:3894819)
    at e.getExtensionDefinition (https://statics.teams.cdn.office.net/hashed/3.2-app.min-7d530ac.js:1:4209837)
    at t.setTabExtensionProperties (https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:3679943)
    at https://statics.teams.cdn.office.net/hashed/3.1-app.min-2a3d537.js:1:3681061
    at f (https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:127:115)
    at https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:127:345
    at m.$eval (https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:142:180)
    at m.$digest (https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:139:290)
    at m.$digest (https://statics.teams.cdn.office.net/hashed/3.2-app.min-7d530ac.js:1:4949579)
    at m.$apply (https://statics.teams.cdn.office.net/hashed/0-angular-jquery.min-eee9041.js:142:474) undefined
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
_#/conversations/General?threadId=19:9fd294b76a5940108190f8e16f3604e7@thread.tacv2&ctx=channel:1 [DOM] Found 2 elements with non-unique id #tabRemoveBtn: (More info: https://goo.gl/9p2vKq) <button class=​"ts-btn ts-btn-fluent ts-btn-fluent-secondary" id=​"tabRemoveBtn" ng-class=​"{'ts-btn-fluent-secondary':​ btn.secondaryStyle,
                           'ts-btn-fluent-primary':​ !btn.secondaryStyle,
                           'dark-mode':​ darkMode}​" ng-click=​"btn.btnType === 'submit' || btn.func()​" type=​"button" track-click-silent=​"true" ng-disabled=​"!!btn.disabled" ng-bind=​"btn.text" aria-label=​"Back" ng-attr-acc-focus-default=​"{{:​:​btn.isFocusDefault}​}​" data-tid=​"tabInstanceConfiguration-backBtn" role=​"button">​…​</button>​ <button class=​"ts-btn ts-btn-fluent ts-btn-fluent-primary" id=​"tabRemoveBtn" ng-class=​"{'ts-btn-fluent-secondary':​ btn.secondaryStyle,
                           'ts-btn-fluent-primary':​ !btn.secondaryStyle,
                           'dark-mode':​ darkMode}​" ng-click=​"btn.btnType === 'submit' || btn.func()​" type=​"submit" track-click-silent=​"true" ng-disabled=​"!!btn.disabled" ng-bind=​"btn.text" aria-label=​"Save" ng-attr-acc-focus-default=​"{{:​:​btn.isFocusDefault}​}​" data-tid=​"tabInstanceConfiguration-saveBtn" role=​"button" disabled=​"disabled">​…​</button>​
client.js:1 Uncaught SyntaxError: Unexpected token '<'
config.html?name=BustosAndrew%40soloiron.onmicrosoft.com&tenant=4c9bb9e9-36ed-43a6-8441-e5561da0848b&group=10eed18e-e597-4e72-a8b6-4bd139b6ebbc&theme=default:18 Uncaught ReferenceError: integration is not defined
    at config.html?name=BustosAndrew%40soloiron.onmicrosoft.com&tenant=4c9bb9e9-36ed-43a6-8441-e5561da0848b&group=10eed18e-e597-4e72-a8b6-4bd139b6ebbc&theme=default:18
DevTools failed to load SourceMap: Could not load content for https://teams.microsoft.com/service-worker.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
I looked at the network responses and I noticed that the js and css files are loaded, but the css file returns the exact same response as the js file. The js file also appears as a full html file. I think it makes sense now why I get an unexpected token, but I don't understand why the client.js file is coming up as an html file.

**Comment by BustosAndrew** [comment] 2021-03-08 04:28
I apologize, I meant to say that loading the config page even on my local machine does not work as well.

**Comment by wictorwilen** [comment] 2021-03-08 07:01
Ok. I think the answer is in `Uncaught SyntaxError: Unexpected token '<'`. This is typically seen when you do get an HTML file instead of a JS file - in case of a 404 for example.

When I test to download the JS file using `https://www.boxintegrationapi.com/scripts/client.js` - I do get an HTML file, the `config.html` of your solution. Looks like something is misconfigured on your web server end

**Comment by BustosAndrew** [comment] 2021-03-08 09:32
Do I need to preload the js and css files in my _headers file? I read on mozilla that I should do that because it seems that content can get blocked if I don't. Here is the link for reference: [click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content). If needed, you should probably add this as an update to your teams generator. I'll see if it does anything good. Edit: still having the same issue. Is it because in the tab ts file that the index, config and html files are used with PreventIFrame? This specific one is under the server folder.

**Comment by wictorwilen** [comment] 2021-03-08 12:28
No. You don't have to do that. Somehow your web server is misconfigured. 

If I run `curl https://www.boxintegrationapi.com/scripts/client.js` I get the following:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Box Tab: Configuration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- inject:css -->
    <link rel="stylesheet" href="/styles/main.css">
    <!-- endinject -->
  </head>

  <body>
    <div id="app">Loading...</div>
    <!-- inject:js -->
    <script src="/scripts/client.js"></script>
    <!-- endinject -->
    <script type="text/javascript">
      integration.render(
        integration.BoxTabConfig,
        document.getElementById('app'),
        {}
      )
    </script>
  </body>
</html>
```

And I do get exactly the same for all the different requests I run towards that domain. For instance `curl https://www.boxintegrationapi.com/foo.bar` also gives me that HTML code.

**Comment by BustosAndrew** [comment] 2021-03-08 20:04
What is the external label for? Oh and it shows the config html file because in my _redirects file I have the site automatically route to it. This is when someone enters an unknown path. On netlify and for SPA, it is best to redirect to a default web page in case of any errors during navigation. I had it set to index before, but I thought I needed to redirect to the config page so people can finish the tab setup? I did this because the setup page on teams would instead load the view for the regular index page, not the tab's index or config page.

**Comment by BustosAndrew** [comment] 2021-03-09 04:08
A friend just helped me realize that netlify doesn't work well with express, unless it is serving static tsx files. After deploying to Heroku, it renders the main webpage just fine. I have not tested the tab pages just yet. I will let you know what happens. Edit: it works perfectly now and all the tab pages work great on teams. I think you should mention that your generator doesn't work with netlify. Netlify seems to only use express for serving static files. Does the generator really generate a server side rendering app?

**Comment by wictorwilen** [comment] 2021-03-09 06:54
Great that you got it to work @BustosAndrew .

This was marked as *external* as it is not a bug in the generator.

Netlify is a hosting provider for static sites - where the whole idea with `generator-teams` is to generate a dynamic site, with `express` as the web server. Which is a requirement if you use features such as bots or messaging extensions or connectors. So yes, the generator really generates a server side rendering app.

**Closed as completed by wictorwilen** 2021-03-09 06:54 UTC
Labels: external
