### ISSUE TITLE
SharePoint SSO ID is not working while running the yo wizard

### ISSUE THREAD

**Issue by diabhoil** [pnp/generator-teams#171] opened 2021-01-20 13:27 UTC
**Describe the bug**
The SharePoint SSO ID "00000003-0000-0ff1-ce00-000000000000" is not validated to true by "validate(input") [TabGenerator.ts](https://github.com/pnp/generator-teams/blob/master/src/tab/TabGenerator.ts) (line 111). Whenever I try a different ID it will work.

**To Reproduce**
1. Execute Yo teams (1.8 path)
2. Answer the question "What is the Application ID to associate with the SSO Tab?" with the id "00000003-0000-0ff1-ce00-000000000000"
3. Nothing will happen

**Expected behavior**
The wizard will continue to the next step asking for the SSO Uri

**Screenshots**
Not possible to screenshot since nothing is happening..the input is just gone.

**Detailed information**
 - Generator version: 2.17.1
 - OS: Windows
 - Node version: 10.16.2
 - Npm version: 6.9.0

**Additional information**
To get SSO with SharePoint pages I need to enter this ID. Should be a valid UUID, at least for Microsoft/SharePoint projects

**Comment by wictorwilen** [comment] 2021-01-21 13:38
Thanks for reporting this. This is not a bug as we do Guid validation (using the `uuid-validate` package) and that is not a correct Guid (it's a handmade version). See this as an example https://runkit.com/wictorwilen/validate-0ff1ce-guid

However, we do an exception for empty guids and should probably make an exception to this specific one as well. I'm adding it to the backlog of v3.

**Comment by wictorwilen** [comment] 2021-01-21 13:39
PS. As a workaround use an empty guid and then update your `.env` file.

**Comment by wictorwilen** [comment] 2021-02-07 13:18
Fixed in 3.0.0 (#176)

**Closed as completed by wictorwilen** 2021-02-07 13:18 UTC
Labels: enhancement
