### ISSUE TITLE
context from useTeams is undefined

### ISSUE THREAD

**Issue by arunakshi** [pnp/generator-teams#163] opened 2020-12-18 06:28 UTC
**Describe the bug**
Trying to get context state information such as EntityId, teamSiteDomain, teamSitePath & channelName in useEffect of Functional component. Getting context state from useTeams as undefined always.

**To Reproduce**
Created the yo teams project with latest generator version and trying to send request to custom graphRouter via custom tab. 

The imports part look like this: 
![image](https://user-images.githubusercontent.com/12812202/102581819-9f668180-4101-11eb-85da-d29655dd6f40.png)

**Expected Behavior**
Expectation is that context is initialized within useTeams and should be available in useEffect() 
![image](https://user-images.githubusercontent.com/12812202/102581923-d5a40100-4101-11eb-9f73-123c68c84027.png)

Since the context is undefined, also tried to initialize microsoftTeams.
![image](https://user-images.githubusercontent.com/12812202/102582478-fc166c00-4102-11eb-8441-1b087c55de8e.png)

However, context is always undefined.

**Current Result**
When cutom tab is loaded, the context is undefined.
![image](https://user-images.githubusercontent.com/12812202/102582388-c5d8ec80-4102-11eb-8761-eb85419218a9.png)

**Detailed information**
Generator version: 2.17.1
OS: Windows
Node version: 10.27.0
Npm version: 6.11.3

**Comment by wictorwilen** [comment] 2020-12-18 07:34
Thanks for reporting this, I'm not able to reproduce this with the following code and I do get a value for `context`.

Also, note that you should not call `microsoftTeams.initialize()` - it's already being called by `useTeams`. And even if you did, that's not giving you the `context`, as that is another method in the Teams JS SDK.

Can you please verify that you run this as a Tab **inside** Microsoft Teams - by checking the `inTeams` state.

``` TypeScript
const [{ inTeams, theme, context }] = useTeams();
const [entityId, setEntityId] = useState<string | undefined>();

useEffect(() => {
    if (inTeams === true) {
        console.log("IN TEAMS");
        microsoftTeams.appInitialization.notifySuccess();
    } else {
        console.log(`inTeams: ${inTeams}`);
    }
}, [inTeams]);

useEffect(() => {
    if (context) {
        console.log("HAS CONTEXT");
        setEntityId(context.entityId);
    }
}, [context]);
```

W

**Comment by arunakshi** [comment] 2020-12-18 11:40
Thanks for the quick reply Wictor. Somehow I had always undefined context. 

I have re-created new teams project and with the same pieces of your code. I have context coming from useTeams() automatically. 

Thank you

**Comment by wictorwilen** [comment] 2020-12-18 12:07
Thanks, I'm closing this one - if it happens again, please re-open.

**Closed as completed by wictorwilen** 2020-12-18 12:07 UTC
Labels: needs more info, request: awaiting validation
