### ISSUE TITLE
The project always fail to deploy to azure

### ISSUE THREAD

**Issue by chenxizhang** [pnp/generator-teams#37] opened 2018-05-27 08:06 UTC
Hi team

The generator is so great for teams developers. I really love it.
I found some issue about deploy process. when I follow the guidance by README.md, I always fail with some error message as below 

=====================

Counting objects: 50, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (46/46), done.
Writing objects: 100% (50/50), 81.04 KiB | 3.86 MiB/s, done.
Total 50 (delta 9), reused 4 (delta 0)
remote: Updating branch 'master'.
remote: ..
remote: Updating submodules.
remote: Preparing deployment for commit id '2fd733df3e'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: /home/site/repository/deploy.cmd: line 1: @if: command not found
remote: /home/site/repository/deploy.cmd: line 3: ::: command not found
remote: /home/site/repository/deploy.cmd: line 4: ::: command not found
remote: /home/site/repository/deploy.cmd: line 5: ::: command not found
remote: /home/site/repository/deploy.cmd: line 6: ::: command not found
remote: /home/site/repository/deploy.cmd: line 8: ::: command not found
remote: /home/site/repository/deploy.cmd: line 9: ::: command not found
remote: /home/site/repository/deploy.cmd: line 11: ::: command not found
remote: /home/site/repository/deploy.cmd: line 12: nul: Permission denied
remote: /home/site/repository/deploy.cmd: line 13: syntax error near unexpected token `('
remote: /home/site/repository/deploy.cmd: line 13: `IF %ERRORLEVEL% NEQ 0 ('
remote:
remote: App container will begin restart within 10 seconds.
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://testnodedeploy.scm.azurewebsites.net:443/testnodedeploy.git
 * [new branch]      master -> master
PS C:\Users\arechen\devdaysteamsbotworkshop> git push azure masterEverything up-to-date
PS C:\Users\arechen\devdaysteamsbotworkshop> git push azure master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 281 bytes | 140.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'e58fe4b054'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: Handling node.js deployment.
remote: Using start-up script dist/server.js from package.json.
remote: Generated web.config.
remote: The package.json file does not specify node.js engine version constraints.
remote: The node.js application will run with the default node.js version 6.9.1.
remote: Selected npm version 3.10.8
remote: ..
remote: npm WARN devdaysteamsbotworkshop@0.0.1 No repository field.
remote: npm WARN devdaysteamsbotworkshop@0.0.1 No license field.
remote:
remote: > devdaysteamsbotworkshop@0.0.1 build D:\home\site\repository
remote: > gulp build
remote:
remote: [08:04:13] Local gulp not found in D:\home\site\repository
remote: [08:04:13] Try running: npm install gulp
remote:
remote: npm ERR! Windows_NT 10.0.14393
remote: npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.8\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
remote: npm ERR! node v6.9.1
remote: npm ERR! npm  v3.10.8
remote: npm ERR! code ELIFECYCLE
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\6.9.1\node.exe" "D:\Program Files (x86)\npm\3.10.8\node_modules\npm\bin\npm-cli.js" run-script build
remote: npm ERR! devdaysteamsbotworkshop@0.0.1 build: `gulp build`
remote: An error has occurred during web site deployment.
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the devdaysteamsbotworkshop@0.0.1 build script 'gulp build'.
remote: npm ERR! Make sure you have the latest version of node.js and npm installed.
remote: npm ERR! If you do, this is most likely a problem with the devdaysteamsbotworkshop package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     gulp build
remote: npm ERR! You can get information on how to open an issue for this project with:remote: npm ERR!     npm bugs devdaysteamsbotworkshop
remote: npm ERR! Or if that isn't available, you can get their info via:
remote: npm ERR!     npm owner ls devdaysteamsbotworkshop
remote: npm ERR! There is likely additional logging output above.
remote:
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     D:\home\site\repository\npm-debug.log
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by wictorwilen** [comment] 2018-06-27 01:05
Hi @chenxizhang  - I've not experienced this myself, will test and come back to you

**Comment by shrenky** [comment] 2018-07-13 05:34
Hi @chenxizhang  - I got similar error: "Local gulp not found in D:\home\site\repository".
because the gulp package belongs to devDependencies, but Azure does not install devDependencies.
I moved all packages in package.json file from devDependencies to dependencies then re-deployed again fixed this issue.

**Comment by wictorwilen** [comment] 2018-08-13 15:48
What is your value of the `NODE_ENV` application setting?

**Comment by shrenky** [comment] 2018-08-23 09:10
@wictorwilen in my environment the value of process.env.NODE_ENV  is  undefined

**Comment by pljfdi** [comment] 2018-09-25 15:57
I've just suffered the the same issue of not specifying a Node version in one of the myriad of ways available.  Azure falls back to 0.10.40, and so the deployment all falls apart (The first issue you have is with iisnode.yml not being found)
So can we have it mentioned somewhere in the documentation/page/readme.md that it's critical to have a NODE_ENV, or "engines"{} or WEBSITE_NODE_DEFAULT_VERSION added in the app. (Or even default package.json to have something like `"engines":{"node" ">8.0.0"} `

**Comment by wictorwilen** [comment] 2018-09-25 17:50
@pljfdi - thanks, I'll ensure to include this in a shortly coming update!

**Comment by RalfBrennscheidt** [comment] 2019-04-13 15:46
Hi!

for me it sadly doesn't work either:
-----------------------------------------
PS C:\Projects\TeamsDev> git push azure master
2019-04-12T14:18:30  Updating branch 'master'.
2019-04-12T14:18:31  Updating submodules.
2019-04-12T14:18:32  Preparing deployment for commit id 'ad19a7bc7d'.
2019-04-12T14:18:32  Running custom deployment command...
2019-04-12T14:18:32  Not setting execute permissions for deploy.cmd
2019-04-12T14:18:32  Running deployment command...
2019-04-12T14:18:32    Command: deploy.cmd
2019-04-12T14:18:32    /opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found
2019-04-12T14:18:32    /opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found
/opt/Kudu/KuduConsole/Scripts/starter.sh deploy.cmd
2019-04-12T14:18:32  
2019-04-12T14:18:32  App container will begin restart within 10 seconds. 

As the initial poster i followed step by step the guidelines in the README.md
Re-created the whole process many times.

<---------------------------->
Correction and NOTE: Please state clearly in the README.md that the WebApp which is being created in Azure HAS TO BE "Windows" and not Linux based. Otherwise it fails as above reported.

However now i receive:

PS C:\Projects\TeamsDev\InnoTeams> git push azure master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 297 bytes | 297.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'd73f57ad1f'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: Handling node.js deployment.
remote: Using start-up script dist/server.js from package.json.
remote: Generated web.config.
remote: The package.json file does not specify node.js engine version constraints.
remote: The node.js application will run with the default node.js version 0.10.40.
remote: Selected npm version 1.4.28
remote: npm WARN package.json innoteams@0.0.1 No repository field.
remote: npm ERR! Error: Method Not Allowed
remote: npm ERR!     at errorResponse (D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:260:10)
remote: npm ERR!     at D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:120:12
remote: npm ERR!     at saved (D:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\npm-registry-client\lib\get.js:167:7)
remote: npm ERR!     at Object.oncomplete (fs.js:108:15)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" install --production
remote:
remote: An error has occurred during web site deployment.
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\repository
remote: npm ERR! node -v v0.10.40
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! code E405
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by cagdasdavulcu** [comment] 2019-04-14 12:43
Hello @RalfBrennscheidt,

I could also reproduce the problem:
2019-04-12T14:18:32 /opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found
2019-04-12T14:18:32 /opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found

1. I think (not sure), that it should be a linux deployment (not windows). 
2. Next topic is, that we should convert the deploy.cmd file from CRLF to LF, thereby the file can be runned on linux environment.
3. I validated the linux web api and identified, there is no folder with name "Kudu" under "opt" folder.

If we can deploy any node js application vai. Kudu Deployment, then we can also deploy the teams application. May be @wictorwilen has more information about that.

**Comment by RalfBrennscheidt** [comment] 2019-04-14 13:01
Hello Sir,

as i wrote in my previous message (in the middle) i would be totally happy if the README.md would clearly instruct that the WebApp in Azure needs to be Windows based, then the world is shiny again.

I actually also solved the second issue i mentioned and the deployment works now totally fine (solution has a bot, tab and message extension.

As "pljfdi" stated it has to do with the node version provided by Azure. Perhaps @wictorwilen forgot to include the patch he mentioned but once i've set in the Azure WebApp the "Application Settings" variable: "WEBSITE_NODE_DEFAULT_VERSION" to "8.10.0" everything worked smoothly with the continuous deployment. A small hint, also set: "SCM_COMMAND_IDLE_TIMEOUT" to something like "1800" since the SCM deployment can idle out some time and this assures it does not crash the deployment script :)

Therefore i highly suggest to simply include those two hints into the README so other do not suffer 2 days of headaches :)

**Comment by cagdasdavulcu** [comment] 2019-04-14 13:58
Thank you for the explanation! It is nice the know that it worked for you.

We would include the notes in readme file.

But i'm still a little bit confused :) I'm testing the Kudu Deployment option (directly pushing of source code from local to azure - not via. VSTS or GitHub)

I added the following parameter in package.json:
"engines": {
    "node": ">8.0.0"
}

And i set the variables "WEBSITE_NODE_DEFAULT_VERSION" to "8.10.0" and  "SCM_COMMAND_IDLE_TIMEOUT" to "1800" and i'm **still getting** the following exception with Kudu Deployment option.

$ git push azure master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 396 bytes | 396.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '5bdc8dfab6'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: Handling node.js deployment.
remote: Using start-up script dist/server.js from package.json.
remote: Generated web.config.
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4, 8.10.0, 8.11.1, 10.0.0, 10.6.0, 10.14.1.
remote: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\dist\iisnode.yml'
remote: Selected node.js version 10.14.1. Use package.json file to choose a different version.
remote: Selected npm version 6.4.1
remote: Updating iisnode.yml at D:\home\site\wwwroot\dist\iisnode.yml
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://xxx.scm.azurewebsites.net:443/xxx.git
   84d8f19..5bdc8df  master -> master

**Comment by RalfBrennscheidt** [comment] 2019-04-14 18:56
Okay, allow me to summarize how i got it working:

1.) Make sure the WebApp you create in Azure is "Windows" (not Linux).
2.) Do not change the package.json (leave it as it is, i tried the same as you and i ended up with the same error) - package.json settings overwrite any setting in the Azure WebApp!
3.) Add the two variables to the Application Settings in the Azure WebApp
4.) Configure continuous deployment via "Local Git" and select Kudu.
5.) I used latest generator

So i assume (in case your WebApp in Azure IS Windows based) just remove the "engine" from the packages.json and it should work.

Hope it works *fingers-crossed*

**Comment by cagdasdavulcu** [comment] 2019-04-14 20:12
it worked! thank you very much! i will include this in the documentation.

**Comment by wictorwilen** [comment] 2019-04-15 08:09
From my experience the `engines` in `package.json` makes all sorts of things fail in Azure. Thanks all for helping sorting this one out. A new and fresh update will shortly be out.

**Comment by wictorwilen** [comment] 2019-04-15 09:04
Thanks all for the contributions. This is now merged in `2.7.0-preview4` (da75026f1944a500aa1b134f978a7564ca18a02e)  which now is published to npmjs.org

**Closed as completed by wictorwilen** 2019-04-15 09:04 UTC
Labels: bug: product
