### ISSUE TITLE
Add connector in teams doesn't work fine

### ISSUE THREAD

**Issue by fabulias** [pnp/generator-teams#117] opened 2020-05-08 03:05 UTC
**Describe the bug**
I have created just a connector with `yo teams`, I can call my ngrok URL with `/api/connector/ping` without problems, also I can to get the config.html page, but when I try to add as a new app in our tenant, the connector offers me select a color Blue or Orange (then I add another color and the color was shown).

![teamsDemoConnector](https://user-images.githubusercontent.com/10964484/81365463-2bb5be00-90b6-11ea-8206-acc8aec32477.PNG)

But...when I press `Save`, I haven't can continue with the tutorial. 

**To Reproduce**
1. Do `yo teams` and select a `connector`, also create a connector in the Connector Dashboard Portal.
2. Do `gulp ngrok-serve`
3. Try to add a new custom app to Microsoft teams.

**Expected behavior**
A positive message like `Settings saved successfully`.

**Screenshots**

**Detailed information**
 - Generator version: 3.1.1
 - OS: Windows 10
 - Node version: v10.16.3
 - Npm version: 6.9.0

**Additional information**
Before, I have created a tab and a bot, I could add them to our Microsoft Teams without problems.

**Comment by wictorwilen** [comment] 2020-05-08 08:31
As you can see Microsoft Teams reports that it's unable to save the connector (see the text in the bottom of your screenshot). That message is typically shown when you have misconfigured your Connector in the connector portal, or using the wrong Ids. Sometimes you might get a hint of what's wrong by opening the web browser developer tools and check for any error messages.

This is not a bug in the generator, but rather either a bug in the custom code or a misconfigured connector.

Please share any error messages, your connector portal configuration and we will help you sort this out.

**Comment by wictorwilen** [comment] 2020-05-13 14:54
@fabulias- any update on this, or can I close this issue?

**Comment by wictorwilen** [comment] 2020-06-08 08:29
Closing this as there's no response. Feel free to open again if required.

**Closed as completed by wictorwilen** 2020-06-08 08:29 UTC
